shibbolethsp:
  hostname: shib-pp
  domainname: ad.universite-lyon.fr
  build: .
  environment:
    VIRTUAL_HOST: nuxeopp.mom.fr
    VIRTUAL_PROTO: https
  links:
    - nuxeo
  ports:
    - "443"
nuxeo:
  hostname: nuxeo-pp
  image: nuxeodocker_nuxeo
  domainname: ad.universite-lyon.fr
  environment:
    PACKAGES: "nuxeo-drive nuxeo-diff nuxeo-virtualnavigation nuxeo-dam nuxeo-spreadsheet nuxeo-template-rendering nuxeo-web-mobile easyshare"
    TEMPLATES: "postgresql,drive"
  volumes:
    - /mom-data-pp:/platform/etc/data
