shibbolethsp:
  hostname: shib-pp
  domainname: ad.universite-lyon.fr
  build: .
  environment:
    VIRTUAL_HOST: nuxeo.universite-lyon.fr
    VIRTUAL_PROTO: https
  links:
    - nuxeo
  ports:
    - "443"
nuxeo:
  hostname: nuxeo-pp
  domainname: ad.universite-lyon.fr
  environment:
    TEMPLATES: "postgresql,drive,/platform/etc/data/conf/templates/shibboleth"
  volumes:
    - /data-pp:/platform/etc/data
