shibbolethsp:
  hostname: shib-pp
  domainname: ad.universite-lyon.fr
  build: .
  environment:
    VIRTUAL_HOST: ish.universite-lyon.fr
    VIRTUAL_PROTO: https
  links:
    - nuxeo
  ports:
    - "443"
nuxeo:
  hostname: nuxeo-pp
  image: nuxeodocker_nuxeo
  domainname: ad.universite-lyon.fr
  environment:
    PACKAGES: "nuxeo-drive shibboleth-authentication nuxeo-diff nuxeo-virtualnavigation nuxeo-dam nuxeo-spreadsheet nuxeo-template-rendering nuxeo-web-mobile"
    PACKAGES2: "nuxeo-dam-compat"
    TEMPLATES: "postgresql,drive,dam,/platform/etc/data/conf/templates/shibboleth"
  volumes:
    - /ish-data-pp:/platform/etc/data
