nuxeo:
  hostname: nuxeo
  # image: registry.universite-lyon.fr/nuxeodocker/nuxeo:7.10-HF17-1.0.0
  build: ../nuxeo-docker/
  environment:
    VIRTUAL_HOST: docker.local
    PACKAGES: "nuxeo-drive shibboleth-authentication nuxeo-diff nuxeo-virtualnavigation nuxeo-dam nuxeo-spreadsheet nuxeo-template-rendering nuxeo-web-mobile nuxeo-platform-user-registration nuxeo-shibboleth-invitation"
    # PACKAGES2: "/platform/etc/data/marketplace/marketplace-multidomain-userworkspace-1.1.1-ISH-SNAPSHOT.zip"
    # PACKAGES2: "/platform/etc/data/conf/marketplace/marketplace-CustomLoginUDL-1.2.4-SNAPSHOT.zip"
    TEMPLATES: "default,drive,/platform/etc/data/conf/templates/shibboleth"
    LAUNCHER_DEBUG: " -Dlog4j.configuration=file:/platform/etc/data/log4j.xml "
    DOCKER_HOST: ${HOSTNAME}
  volumes:
    - /Users/vincent/Documents/dev/java/nuxeo-udl/etc_data:/platform/etc/data
    - /Users/vincent/Documents/dev/java/nuxeo-udl/etc_data/CERT-CA.cer:/tmp/CERT-CA.cer:ro
  ports:
    - 8080
shibbolethsp:
  hostname: shib
  # image: v20100/nuxeo-shibboleth-docker
  build: ./
  environment:
    VIRTUAL_HOST: nuxeo.universite-lyon.fr
    VIRTUAL_PROTO: https
    OTHER_NGINX_PARAMETERS: "ignore_invalid_headers off;"
  links:
    - nuxeo
  ports:
    - "443"
  volumes:
    - /Users/vincent/Documents/dev/java/nuxeo-udl/etc_data/sp-cert.pem:/etc/shibboleth/sp-cert.pem:ro
    - /Users/vincent/Documents/dev/java/nuxeo-udl/etc_data/sp-key.pem:/etc/shibboleth/sp-key.pem:ro
